/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodsRouteImport } from './routes/methods'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SimulateRouteImport } from './routes/simulate'
import { Route as ThesisRouteImport } from './routes/thesis'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodsRoute = MethodsRouteImport.update({
  id: '/methods',
  path: '/methods',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulateRoute = SimulateRouteImport.update({
  id: '/simulate',
  path: '/simulate',
  getParentRoute: () => rootRouteImport,
} as any)
const ThesisRoute = ThesisRouteImport.update({
  id: '/thesis',
  path: '/thesis',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/methods': typeof MethodsRoute
  '/results': typeof ResultsRoute
  '/simulate': typeof SimulateRoute
  '/thesis': typeof ThesisRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/methods': typeof MethodsRoute
  '/results': typeof ResultsRoute
  '/simulate': typeof SimulateRoute
  '/thesis': typeof ThesisRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/methods': typeof MethodsRoute
  '/results': typeof ResultsRoute
  '/simulate': typeof SimulateRoute
  '/thesis': typeof ThesisRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/methods' | '/results' | '/simulate' | '/thesis'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/methods' | '/results' | '/simulate' | '/thesis'
  id: '__root__' | '/' | '/methods' | '/results' | '/simulate' | '/thesis'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodsRoute: typeof MethodsRoute
  ResultsRoute: typeof ResultsRoute
  SimulateRoute: typeof SimulateRoute
  ThesisRoute: typeof ThesisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methods': {
      id: '/methods'
      path: '/methods'
      fullPath: '/methods'
      preLoaderRoute: typeof MethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulate': {
      id: '/simulate'
      path: '/simulate'
      fullPath: '/simulate'
      preLoaderRoute: typeof SimulateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thesis': {
      id: '/thesis'
      path: '/thesis'
      fullPath: '/thesis'
      preLoaderRoute: typeof ThesisRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodsRoute: MethodsRoute,
  ResultsRoute: ResultsRoute,
  SimulateRoute: SimulateRoute,
  ThesisRoute: ThesisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
